### Get Ditto information
GET http://localhost:1234/pokemon/ditto
### Create a new pokemon
POST http://localhost:1234/pokemon
Content-Type: application/json

{
  "name": "ditto",
  "type": "normal",
  "moves": ["transform"]
}

### Error 404 
GET http://localhost:1234/pokemon/missing